development:
  access_key_id: AKIAI3DJWYSZUK74RCIA
  secret_access_key: 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
  bucket: purrrbucket
    
test:
  access_key_id: AKIAI3DJWYSZUK74RCIA
  secret_access_key: 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
  bucket: purrrbucket
  
production:
  access_key_id: AKIAI3DJWYSZUK74RCIA
  secret_access_key: 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
  bucket: purrrbucket
