development:
  access_key_id: 
  secret_access_key: 
  bucket: purrrbucket
    
test:
  access_key_id: 
  secret_access_key: 
  bucket: purrrbucket
  
production:
  access_key_id: 
  secret_access_key: 
  bucket: purrrbucket
